FLAGS = -Wall -g
CC = gcc	#keep the abilty to change the compiler


sequenceSearch.o: sequenceSearch.c sequenceSearch.h
	$(CC) $(FLAGS) -c sequenceSearch.c

.PHONY: clean

clean:
	rm -f *.o *.a *.so *.gch a.out